const ACTION_TYPES = {
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_DONE_TODOS: 'DELETE_DONE_TODOS',

  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
};

export default ACTION_TYPES;
