const ACTION_TYPES = {
  GET_TODOS_ACTION: 'GET_TODOS_ACTION',
  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_ERROR: 'GET_TODOS_ERROR',

  CREATE_TODO_ACTION: 'CREATE_TODO_ACTION',
  CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_ERROR: 'CREATE_TODO_ERROR',

  DELETE_TODO_ACTION: 'DELETE_TODO_ACTION',
  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',

  UPDATE_TODO_ACTION: 'UPDATE_TODO_ACTION',
  UPDATE_TODO_REQUEST: 'UPDATE_TODO_REQUEST',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_ERROR: 'UPDATE_TODO_ERROR',

  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
};

export default ACTION_TYPES;
